apiVersion: 1
datasources:
- access: proxy
  isDefault: true
  jsonData:
    requestUrl: http://deepflow-server:20416
    traceUrl: http://deepflow-app:20418
  name: DeepFlow
  type: deepflow-querier-datasource
  uid: DeepFlow
  url: null
- jsonData:
    port: 9000
    server: 'deepflow-clickhouse'
    username: default
  name: DeepFlow ClickHouse
  secureJsonData:
    password: ""
  type: grafana-clickhouse-datasource
  uid: DeepFlow ClickHouse
- database: deepflow
  jsonData:
    connMaxLifetime: 14400
    maxIdleConns: 5
    maxOpenConns: 5
  name: DeepFlow MySQL
  password: deepflow
  secureJsonData:
    password: 'deepflow'
  type: mysql
  uid: DeepFlow MySQL
  url: 'deepflow-mysql:30130'
  user: root
